### ISSUE TITLE
Does EUDEditor2 support the ealier vision(1.16.1) of SC?

### ISSUE THREAD

**Issue by dglxlcl** [armoha/EUDEditor#2]
I can see the option(choose 1.16.1 or remastered) in Eud-editor2.0.17.9.7's setting，and i choosed 1.16.(the version of euddraft is 0.9.2.0).
But after i compiled and saved the scx map ,the sc1.16.1 could't recognize the map,the error tips is "This scenario is intended for use with a expansion set."
what's wrong with the map ?
euddraft/EUDEditor2 doesn't support the old version game,isn't it?

**Comment by armoha** [comment]
`euddraft 0.9.2.0` only supports StarCraft: Remastered. You should use either `euddraft 0.8.2.1` or `euddraft 0.8.2.9`.
See https://github.com/phu54321/euddraft/issues/20#issuecomment-894626962
> 
> 
>     * For 1.16.1 only, use [`euddraft 0.8.2.1`](https://github.com/phu54321/euddraft/blob/64b77154ff001c799a4f02f3f82ae3589b5767a6/latest/euddraft0.8.2.1.zip).
> 
>     * For both 1.16.1 and SC:R, use [`euddraft 0.8.2.9`](https://github.com/phu54321/euddraft/blob/64b77154ff001c799a4f02f3f82ae3589b5767a6/latest/euddraft0.8.2.9.zip).
> 
>     * Since `euddraft 0.8.4.7` eagerly adopted _EUDX_, later euddraft only supports StarCraft: Remastered.
> 
>     * euddraft version guide (Korean): https://cafe.naver.com/edac/77050
> 
> 
> If you want to run already existing SC:R map in 1.16.1, [**EUDEnable: Remastered**](https://github.com/saintofidiocy/EUDEnableR) is ChaosLauncher plugin for StarCraft 1.16 to run SC:R Maps. You can download `EUDEnableR.bwl` and load this plugin.
